package br.edu.ifpr.comat.entity;
// Generated 23/09/2013 21:24:33 by Hibernate Tools 3.2.1.GA



/**
 * TbCidade generated by hbm2java
 */
public class TbCidade  implements java.io.Serializable {


     private TbCidadeId id;

    public TbCidade() {
    }

    public TbCidade(TbCidadeId id) {
       this.id = id;
    }
   
    public TbCidadeId getId() {
        return this.id;
    }
    
    public void setId(TbCidadeId id) {
        this.id = id;
    }




}


