package br.edu.ifpr.comat.entity;
// Generated 23/09/2013 21:24:33 by Hibernate Tools 3.2.1.GA



/**
 * TbCidadeId generated by hbm2java
 */
public class TbCidadeId  implements java.io.Serializable {


     private String ufEst;
     private String cidadeCid;

    public TbCidadeId() {
    }

    public TbCidadeId(String ufEst, String cidadeCid) {
       this.ufEst = ufEst;
       this.cidadeCid = cidadeCid;
    }
   
    public String getUfEst() {
        return this.ufEst;
    }
    
    public void setUfEst(String ufEst) {
        this.ufEst = ufEst;
    }
    public String getCidadeCid() {
        return this.cidadeCid;
    }
    
    public void setCidadeCid(String cidadeCid) {
        this.cidadeCid = cidadeCid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TbCidadeId) ) return false;
		 TbCidadeId castOther = ( TbCidadeId ) other; 
         
		 return ( (this.getUfEst()==castOther.getUfEst()) || ( this.getUfEst()!=null && castOther.getUfEst()!=null && this.getUfEst().equals(castOther.getUfEst()) ) )
 && ( (this.getCidadeCid()==castOther.getCidadeCid()) || ( this.getCidadeCid()!=null && castOther.getCidadeCid()!=null && this.getCidadeCid().equals(castOther.getCidadeCid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUfEst() == null ? 0 : this.getUfEst().hashCode() );
         result = 37 * result + ( getCidadeCid() == null ? 0 : this.getCidadeCid().hashCode() );
         return result;
   }   


}


