package br.edu.ifpr.comat.entity;
// Generated 23/09/2013 21:24:33 by Hibernate Tools 3.2.1.GA



/**
 * TbCliente generated by hbm2java
 */
public class TbCliente  implements java.io.Serializable {


     private Integer idCli;
     private Integer statusCli;
     private String emailCli;
     private String siteCli;
     private String telefoneCli;
     private String obsCli;
     private Integer tbEnderecoIdEnd;

    public TbCliente() {
    }

    public TbCliente(Integer statusCli, String emailCli, String siteCli, String telefoneCli, String obsCli, Integer tbEnderecoIdEnd) {
       this.statusCli = statusCli;
       this.emailCli = emailCli;
       this.siteCli = siteCli;
       this.telefoneCli = telefoneCli;
       this.obsCli = obsCli;
       this.tbEnderecoIdEnd = tbEnderecoIdEnd;
    }
   
    public Integer getIdCli() {
        return this.idCli;
    }
    
    public void setIdCli(Integer idCli) {
        this.idCli = idCli;
    }
    public Integer getStatusCli() {
        return this.statusCli;
    }
    
    public void setStatusCli(Integer statusCli) {
        this.statusCli = statusCli;
    }
    public String getEmailCli() {
        return this.emailCli;
    }
    
    public void setEmailCli(String emailCli) {
        this.emailCli = emailCli;
    }
    public String getSiteCli() {
        return this.siteCli;
    }
    
    public void setSiteCli(String siteCli) {
        this.siteCli = siteCli;
    }
    public String getTelefoneCli() {
        return this.telefoneCli;
    }
    
    public void setTelefoneCli(String telefoneCli) {
        this.telefoneCli = telefoneCli;
    }
    public String getObsCli() {
        return this.obsCli;
    }
    
    public void setObsCli(String obsCli) {
        this.obsCli = obsCli;
    }
    public Integer getTbEnderecoIdEnd() {
        return this.tbEnderecoIdEnd;
    }
    
    public void setTbEnderecoIdEnd(Integer tbEnderecoIdEnd) {
        this.tbEnderecoIdEnd = tbEnderecoIdEnd;
    }




}


