package br.edu.ifpr.comat.entity;
// Generated 23/09/2013 21:24:33 by Hibernate Tools 3.2.1.GA



/**
 * TbContato generated by hbm2java
 */
public class TbContato  implements java.io.Serializable {


     private Integer idCon;
     private String nomeCon;
     private String telefoneCon;
     private String celularCon;
     private String emailCon;
     private String cargoCon;

    public TbContato() {
    }

    public TbContato(String nomeCon, String telefoneCon, String celularCon, String emailCon, String cargoCon) {
       this.nomeCon = nomeCon;
       this.telefoneCon = telefoneCon;
       this.celularCon = celularCon;
       this.emailCon = emailCon;
       this.cargoCon = cargoCon;
    }
   
    public Integer getIdCon() {
        return this.idCon;
    }
    
    public void setIdCon(Integer idCon) {
        this.idCon = idCon;
    }
    public String getNomeCon() {
        return this.nomeCon;
    }
    
    public void setNomeCon(String nomeCon) {
        this.nomeCon = nomeCon;
    }
    public String getTelefoneCon() {
        return this.telefoneCon;
    }
    
    public void setTelefoneCon(String telefoneCon) {
        this.telefoneCon = telefoneCon;
    }
    public String getCelularCon() {
        return this.celularCon;
    }
    
    public void setCelularCon(String celularCon) {
        this.celularCon = celularCon;
    }
    public String getEmailCon() {
        return this.emailCon;
    }
    
    public void setEmailCon(String emailCon) {
        this.emailCon = emailCon;
    }
    public String getCargoCon() {
        return this.cargoCon;
    }
    
    public void setCargoCon(String cargoCon) {
        this.cargoCon = cargoCon;
    }




}


