package br.edu.ifpr.comat.entity;
// Generated 23/09/2013 21:24:33 by Hibernate Tools 3.2.1.GA



/**
 * TbContatosClienteId generated by hbm2java
 */
public class TbContatosClienteId  implements java.io.Serializable {


     private int idCon;
     private int idCli;

    public TbContatosClienteId() {
    }

    public TbContatosClienteId(int idCon, int idCli) {
       this.idCon = idCon;
       this.idCli = idCli;
    }
   
    public int getIdCon() {
        return this.idCon;
    }
    
    public void setIdCon(int idCon) {
        this.idCon = idCon;
    }
    public int getIdCli() {
        return this.idCli;
    }
    
    public void setIdCli(int idCli) {
        this.idCli = idCli;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TbContatosClienteId) ) return false;
		 TbContatosClienteId castOther = ( TbContatosClienteId ) other; 
         
		 return (this.getIdCon()==castOther.getIdCon())
 && (this.getIdCli()==castOther.getIdCli());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCon();
         result = 37 * result + this.getIdCli();
         return result;
   }   


}


