package br.edu.ifpr.comat.entity;
// Generated 23/09/2013 21:24:33 by Hibernate Tools 3.2.1.GA



/**
 * TbContatosCliente generated by hbm2java
 */
public class TbContatosCliente  implements java.io.Serializable {


     private TbContatosClienteId id;

    public TbContatosCliente() {
    }

    public TbContatosCliente(TbContatosClienteId id) {
       this.id = id;
    }
   
    public TbContatosClienteId getId() {
        return this.id;
    }
    
    public void setId(TbContatosClienteId id) {
        this.id = id;
    }




}


