package br.edu.ifpr.comat.entity;
// Generated 23/09/2013 21:24:33 by Hibernate Tools 3.2.1.GA



/**
 * TbEndereco generated by hbm2java
 */
public class TbEndereco  implements java.io.Serializable {


     private Integer idEnd;
     private String tipoEnd;
     private String logradouroEnd;
     private int numeroEnd;
     private String complementoEnd;
     private String bairroEnd;
     private int cepEnd;
     private int idCid;
     private String ufEst;
     private String cidadeCid;

    public TbEndereco() {
    }

	
    public TbEndereco(String tipoEnd, String logradouroEnd, int numeroEnd, int cepEnd, int idCid, String ufEst, String cidadeCid) {
        this.tipoEnd = tipoEnd;
        this.logradouroEnd = logradouroEnd;
        this.numeroEnd = numeroEnd;
        this.cepEnd = cepEnd;
        this.idCid = idCid;
        this.ufEst = ufEst;
        this.cidadeCid = cidadeCid;
    }
    public TbEndereco(String tipoEnd, String logradouroEnd, int numeroEnd, String complementoEnd, String bairroEnd, int cepEnd, int idCid, String ufEst, String cidadeCid) {
       this.tipoEnd = tipoEnd;
       this.logradouroEnd = logradouroEnd;
       this.numeroEnd = numeroEnd;
       this.complementoEnd = complementoEnd;
       this.bairroEnd = bairroEnd;
       this.cepEnd = cepEnd;
       this.idCid = idCid;
       this.ufEst = ufEst;
       this.cidadeCid = cidadeCid;
    }
   
    public Integer getIdEnd() {
        return this.idEnd;
    }
    
    public void setIdEnd(Integer idEnd) {
        this.idEnd = idEnd;
    }
    public String getTipoEnd() {
        return this.tipoEnd;
    }
    
    public void setTipoEnd(String tipoEnd) {
        this.tipoEnd = tipoEnd;
    }
    public String getLogradouroEnd() {
        return this.logradouroEnd;
    }
    
    public void setLogradouroEnd(String logradouroEnd) {
        this.logradouroEnd = logradouroEnd;
    }
    public int getNumeroEnd() {
        return this.numeroEnd;
    }
    
    public void setNumeroEnd(int numeroEnd) {
        this.numeroEnd = numeroEnd;
    }
    public String getComplementoEnd() {
        return this.complementoEnd;
    }
    
    public void setComplementoEnd(String complementoEnd) {
        this.complementoEnd = complementoEnd;
    }
    public String getBairroEnd() {
        return this.bairroEnd;
    }
    
    public void setBairroEnd(String bairroEnd) {
        this.bairroEnd = bairroEnd;
    }
    public int getCepEnd() {
        return this.cepEnd;
    }
    
    public void setCepEnd(int cepEnd) {
        this.cepEnd = cepEnd;
    }
    public int getIdCid() {
        return this.idCid;
    }
    
    public void setIdCid(int idCid) {
        this.idCid = idCid;
    }
    public String getUfEst() {
        return this.ufEst;
    }
    
    public void setUfEst(String ufEst) {
        this.ufEst = ufEst;
    }
    public String getCidadeCid() {
        return this.cidadeCid;
    }
    
    public void setCidadeCid(String cidadeCid) {
        this.cidadeCid = cidadeCid;
    }




}


