package br.edu.ifpr.comat.entity;
// Generated 23/09/2013 21:24:33 by Hibernate Tools 3.2.1.GA



/**
 * TbEstado generated by hbm2java
 */
public class TbEstado  implements java.io.Serializable {


     private String ufEst;
     private String estadoEst;

    public TbEstado() {
    }

    public TbEstado(String ufEst, String estadoEst) {
       this.ufEst = ufEst;
       this.estadoEst = estadoEst;
    }
   
    public String getUfEst() {
        return this.ufEst;
    }
    
    public void setUfEst(String ufEst) {
        this.ufEst = ufEst;
    }
    public String getEstadoEst() {
        return this.estadoEst;
    }
    
    public void setEstadoEst(String estadoEst) {
        this.estadoEst = estadoEst;
    }




}


