package br.edu.ifpr.comat.entity;
// Generated 23/09/2013 21:24:33 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TbPessoaFisica generated by hbm2java
 */
public class TbPessoaFisica  implements java.io.Serializable {


     private long cpfPfi;
     private int rgPfi;
     private String nomePfi;
     private Date dataNascPfi;
     private String celularCli;
     private int idCli;

    public TbPessoaFisica() {
    }

	
    public TbPessoaFisica(long cpfPfi, int rgPfi, String nomePfi, int idCli) {
        this.cpfPfi = cpfPfi;
        this.rgPfi = rgPfi;
        this.nomePfi = nomePfi;
        this.idCli = idCli;
    }
    public TbPessoaFisica(long cpfPfi, int rgPfi, String nomePfi, Date dataNascPfi, String celularCli, int idCli) {
       this.cpfPfi = cpfPfi;
       this.rgPfi = rgPfi;
       this.nomePfi = nomePfi;
       this.dataNascPfi = dataNascPfi;
       this.celularCli = celularCli;
       this.idCli = idCli;
    }
   
    public long getCpfPfi() {
        return this.cpfPfi;
    }
    
    public void setCpfPfi(long cpfPfi) {
        this.cpfPfi = cpfPfi;
    }
    public int getRgPfi() {
        return this.rgPfi;
    }
    
    public void setRgPfi(int rgPfi) {
        this.rgPfi = rgPfi;
    }
    public String getNomePfi() {
        return this.nomePfi;
    }
    
    public void setNomePfi(String nomePfi) {
        this.nomePfi = nomePfi;
    }
    public Date getDataNascPfi() {
        return this.dataNascPfi;
    }
    
    public void setDataNascPfi(Date dataNascPfi) {
        this.dataNascPfi = dataNascPfi;
    }
    public String getCelularCli() {
        return this.celularCli;
    }
    
    public void setCelularCli(String celularCli) {
        this.celularCli = celularCli;
    }
    public int getIdCli() {
        return this.idCli;
    }
    
    public void setIdCli(int idCli) {
        this.idCli = idCli;
    }




}


