/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifpr.comat.ui;

/**
 *
 * @author Cristhiano Konczak Cardoso <cristhiano@c3info.com.br>
 */
public class ListarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarCliente
     */
    public ListarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGBuscar = new javax.swing.ButtonGroup();
        jpnTitulo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jpnFiltros = new javax.swing.JPanel();
        jteBuscar = new javax.swing.JTextField();
        lbBuscar = new javax.swing.JLabel();
        jckFisicas = new javax.swing.JCheckBox();
        jckJuridicas = new javax.swing.JCheckBox();
        lbTipoPessoas = new javax.swing.JLabel();
        jrdNome = new javax.swing.JRadioButton();
        jrdDocumento = new javax.swing.JRadioButton();
        jrdTelefone = new javax.swing.JRadioButton();
        jpnConsulta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Clientes");

        javax.swing.GroupLayout jpnTituloLayout = new javax.swing.GroupLayout(jpnTitulo);
        jpnTitulo.setLayout(jpnTituloLayout);
        jpnTituloLayout.setHorizontalGroup(
            jpnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(399, Short.MAX_VALUE))
        );
        jpnTituloLayout.setVerticalGroup(
            jpnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        lbBuscar.setForeground(new java.awt.Color(102, 102, 102));
        lbBuscar.setText("Buscar");

        jckFisicas.setSelected(true);
        jckFisicas.setText("Fisicas");

        jckJuridicas.setSelected(true);
        jckJuridicas.setText("Jurídicas");

        lbTipoPessoas.setForeground(new java.awt.Color(102, 102, 102));
        lbTipoPessoas.setText("Tipo de Pessoas");

        btGBuscar.add(jrdNome);
        jrdNome.setSelected(true);
        jrdNome.setText("Nome");

        btGBuscar.add(jrdDocumento);
        jrdDocumento.setText("Documento");

        btGBuscar.add(jrdTelefone);
        jrdTelefone.setText("Telefones");

        javax.swing.GroupLayout jpnFiltrosLayout = new javax.swing.GroupLayout(jpnFiltros);
        jpnFiltros.setLayout(jpnFiltrosLayout);
        jpnFiltrosLayout.setHorizontalGroup(
            jpnFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnFiltrosLayout.createSequentialGroup()
                        .addGroup(jpnFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnFiltrosLayout.createSequentialGroup()
                                .addComponent(lbBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE))
                            .addGroup(jpnFiltrosLayout.createSequentialGroup()
                                .addComponent(jteBuscar)
                                .addGap(38, 38, 38)))
                        .addGroup(jpnFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTipoPessoas)
                            .addGroup(jpnFiltrosLayout.createSequentialGroup()
                                .addComponent(jckFisicas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jckJuridicas)))
                        .addGap(63, 63, 63))
                    .addGroup(jpnFiltrosLayout.createSequentialGroup()
                        .addComponent(jrdNome)
                        .addGap(10, 10, 10)
                        .addComponent(jrdDocumento)
                        .addGap(10, 10, 10)
                        .addComponent(jrdTelefone)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpnFiltrosLayout.setVerticalGroup(
            jpnFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFiltrosLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jpnFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTipoPessoas)
                    .addComponent(lbBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jckFisicas)
                    .addComponent(jckJuridicas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrdNome)
                    .addComponent(jrdDocumento)
                    .addComponent(jrdTelefone))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jpnConsultaLayout = new javax.swing.GroupLayout(jpnConsulta);
        jpnConsulta.setLayout(jpnConsultaLayout);
        jpnConsultaLayout.setHorizontalGroup(
            jpnConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );
        jpnConsultaLayout.setVerticalGroup(
            jpnConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnConsultaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 135, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btGBuscar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBox jckFisicas;
    private javax.swing.JCheckBox jckJuridicas;
    private javax.swing.JPanel jpnConsulta;
    private javax.swing.JPanel jpnFiltros;
    private javax.swing.JPanel jpnTitulo;
    private javax.swing.JRadioButton jrdDocumento;
    private javax.swing.JRadioButton jrdNome;
    private javax.swing.JRadioButton jrdTelefone;
    private javax.swing.JTextField jteBuscar;
    private javax.swing.JLabel lbBuscar;
    private javax.swing.JLabel lbTipoPessoas;
    // End of variables declaration//GEN-END:variables
}
